#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate copy rules and native prebuilt modules from Pantech blob manifests."""
import argparse
import json
from pathlib import Path, PurePosixPath
import re
import struct


def generate(root, scope, manifest, output, camera):
    vendor = output.parent
    # Extraction supplies staged blobs; isolated regeneration uses the source tree.
    blob_vendor = vendor if (vendor / 'proprietary').is_dir() else root / 'vendor/pantech' / scope
    prefix = 'pantech_' + scope.replace('-', '_')
    defaults = prefix + '_blob_defaults'
    copies, packages, modules = [], [], []
    camera_module = None
    destinations = set()
    for line in manifest.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith('#'):
            continue
        source, destination = line.split('|', 1)[0].split(':', 1)
        destination = destination.replace('$(TARGET_COPY_OUT_VENDOR)/', 'vendor/', 1)
        destination = destination.removeprefix('system/')
        if not destination.startswith('vendor/'):
            raise ValueError(f'Unsupported destination: {destination}')
        if destination in destinations:
            continue
        destinations.add(destination)
        blob = blob_vendor / 'proprietary' / source
        with blob.open('rb') as stream:
            header = stream.read(20)
        native = destination.startswith(('vendor/bin/', 'vendor/lib/'))
        if header[:4] != b'\x7fELF' or not native:
            copies.append(f'vendor/pantech/{scope}/proprietary/{source}:$(TARGET_COPY_OUT_VENDOR)/{destination[7:]}')
            continue
        if header[4:6] != b'\x01\x01' or struct.unpack_from('<H', header, 18)[0] != 40:
            raise ValueError(f'Expected a 32-bit ARM blob: {blob}')
        binary = destination.startswith('vendor/bin/')
        relative = PurePosixPath(destination).relative_to('vendor/bin' if binary else 'vendor/lib')
        filename = relative.name
        if not binary and not filename.endswith('.so'):
            raise ValueError(f'Expected a shared library: {destination}')
        name = prefix + '_' + re.sub(r'[^a-zA-Z0-9_]', '_', destination[7:])
        kind = 'cc_prebuilt_binary' if binary else 'cc_prebuilt_library_shared'
        lines = [kind + ' {', f'    name: {json.dumps(name)},',
                 f'    defaults: [{json.dumps(defaults)}],',
                 f'    stem: {json.dumps(filename if binary else filename[:-3])},',
                 '    arch: {', '        arm: {', '            enabled: true,',
                 f'            srcs: [{json.dumps("proprietary/" + source)}],',
                 '        },', '    },']
        if filename == 'hci_qcomm_init':
            lines += ['    check_elf_files: true,',
                      '    shared_libs: ["libcutils", "libc++", "libdl", "libc", "libm"],']
        if str(relative.parent) != '.':
            lines.append(f'    relative_install_path: {json.dumps(str(relative.parent))},')
        lines.append('}')
        modules.append('\n'.join(lines))
        if source == camera:
            camera_module = name
        else:
            packages.append(name)

    bp = '''// Generated by device/pantech/ef52/generate-prebuilts.py. Do not edit.
// SPDX-License-Identifier: Apache-2.0

cc_defaults {
    name: DEFAULTS,
    vendor: true,
    compile_multilib: "32",
    enabled: false,
    strip: { none: true },
    // Legacy blobs use private ABI dependencies and runtime compatibility shims.
    // Preserve their original ELF contents and existing runtime dependency layout.
    check_elf_files: false,
    system_shared_libs: [],
    stl: "none",
}
'''.replace('DEFAULTS', json.dumps(defaults))
    firmware_group = ''
    if scope == 'ef52':
        firmware_group = '\nfilegroup {\n    name: "ef52_pn544_firmware",\n    srcs: ["proprietary/vendor/etc/firmware/libpn544_fw.so"],\n}\n'
    (vendor / 'Android.bp').write_text(bp + '\n' + '\n\n'.join(modules) + '\n' + firmware_group)
    mk = '# Generated by device/pantech/ef52/generate-prebuilts.py. Do not edit.\n# SPDX-License-Identifier: Apache-2.0\n\n'
    if camera_module:
        mk += '# Devices with a different camera daemon must not install this blob.\n'
        mk += 'ifeq ($(filter ef50l ef48s ef49k,$(TARGET_DEVICE)),)\n'
        mk += f'PRODUCT_PACKAGES += {camera_module}\nendif\n\n'
    for variable, entries in [('PRODUCT_PACKAGES', packages), ('PRODUCT_COPY_FILES', copies)]:
        if entries:
            mk += variable + ' += \\\n    ' + ' \\\n    '.join(entries) + '\n\n'
    output.write_text(mk.rstrip() + "\n")
    print(f'{scope}: {len(modules)} native prebuilts, {len(copies)} data/firmware copies')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('root', type=Path)
    parser.add_argument('scope')
    parser.add_argument('manifest', type=Path)
    parser.add_argument('output', type=Path)
    parser.add_argument('camera', nargs='?', default='')
    args = parser.parse_args()
    generate(args.root, args.scope, args.manifest, args.output, args.camera)
