#!/bin/sh
set -e

VENDOR=pantech
DEVICE=ef52
COMMON=msm8960-common

DEVICE_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
ANDROID_ROOT=$(CDPATH= cd -- "$DEVICE_DIR/../../.." && pwd)
VENDOR_ROOT=${VENDOR_ROOT:-"$ANDROID_ROOT/vendor/$VENDOR"}

mkdir -p "$VENDOR_ROOT/$DEVICE" "$VENDOR_ROOT/$COMMON"

emit_copy_files() {
    python3 "$DEVICE_DIR/generate-prebuilts.py" "$ANDROID_ROOT" "$1" "$2" "$3" "$4"
}

emit_copy_files "$DEVICE" "$DEVICE_DIR/proprietary-blobs.txt" \
    "$VENDOR_ROOT/$DEVICE/$DEVICE-vendor-blobs.mk" ""
emit_copy_files "$COMMON" "$DEVICE_DIR/../$COMMON/proprietary-blobs.txt" \
    "$VENDOR_ROOT/$COMMON/$COMMON-vendor-blobs.mk" "vendor/bin/mm-qcamera-daemon"

for SCOPE in "$DEVICE" "$COMMON"; do
cat > "$VENDOR_ROOT/$SCOPE/$SCOPE-vendor.mk" <<EOF
# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/$VENDOR/$DEVICE/setup-makefiles.sh

# Live wallpaper packages
PRODUCT_PACKAGES := \\
    LiveWallpapersPicker \\
    librs_jni

# Pick up overlay for features that depend on non-open-source files
DEVICE_PACKAGE_OVERLAYS := vendor/$VENDOR/$SCOPE/overlay

\$(call inherit-product, vendor/$VENDOR/$SCOPE/$SCOPE-vendor-blobs.mk)
EOF

cat > "$VENDOR_ROOT/$SCOPE/BoardConfigVendor.mk" <<EOF
# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/$VENDOR/$DEVICE/setup-makefiles.sh

USE_CAMERA_STUB := false
EOF
done
