#!/bin/sh
set -e

VENDOR=pantech
DEVICE=ef52
COMMON=msm8960-common

DEVICE_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
ANDROID_ROOT=$(CDPATH= cd -- "$DEVICE_DIR/../../.." && pwd)

emit_copy_files() {
    SCOPE=$1
    MANIFEST=$2
    OUTPUT=$3
    SKIP=$4

    {
        cat <<EOF
# Copyright (C) 2020 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/$VENDOR/$DEVICE/setup-makefiles.sh

EOF
        if [ -n "$SKIP" ]; then
            cat <<EOF
# Detect devices that use a different camera daemon.
ifeq (\$(filter ef50l ef48s ef49k,\$(TARGET_DEVICE)),)
PRODUCT_COPY_FILES += \\
    vendor/$VENDOR/$SCOPE/proprietary/$SKIP:system/$SKIP
endif

EOF
        fi

        echo "PRODUCT_COPY_FILES += \\"
        ENTRIES=$(grep -v '^#' "$MANIFEST" | grep -v '^$' | sed 's/|.*//')
        if [ -n "$SKIP" ]; then
            ENTRIES=$(printf '%s\n' "$ENTRIES" | grep -v "^$SKIP:")
        fi
        COUNT=$(printf '%s\n' "$ENTRIES" | wc -l)
        printf '%s\n' "$ENTRIES" | while IFS= read -r ENTRY; do
            SOURCE=${ENTRY%%:*}
            DESTINATION=${ENTRY#*:}
            case "$DESTINATION" in
                vendor/*)
                    DESTINATION="\$(TARGET_COPY_OUT_VENDOR)/${DESTINATION#vendor/}"
                    ;;
            esac
            COUNT=$((COUNT - 1))
            if [ "$COUNT" -eq 0 ]; then
                printf '    vendor/%s/%s/proprietary/%s:%s\n' "$VENDOR" "$SCOPE" "$SOURCE" "$DESTINATION"
            else
                printf '    vendor/%s/%s/proprietary/%s:%s \\\n' "$VENDOR" "$SCOPE" "$SOURCE" "$DESTINATION"
            fi
        done
    } > "$OUTPUT"
}

emit_copy_files "$DEVICE" "$DEVICE_DIR/proprietary-blobs.txt" \
    "$ANDROID_ROOT/vendor/$VENDOR/$DEVICE/$DEVICE-vendor-blobs.mk" ""
emit_copy_files "$COMMON" "$DEVICE_DIR/../$COMMON/proprietary-blobs.txt" \
    "$ANDROID_ROOT/vendor/$VENDOR/$COMMON/$COMMON-vendor-blobs.mk" "vendor/bin/mm-qcamera-daemon"

cat > "$ANDROID_ROOT/vendor/$VENDOR/$DEVICE/$DEVICE-vendor.mk" <<EOF
# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/$VENDOR/$DEVICE/setup-makefiles.sh

# Live wallpaper packages
PRODUCT_PACKAGES := \\
    LiveWallpapers \\
    LiveWallpapersPicker \\
    MagicSmokeWallpapers \\
    VisualizationWallpapers \\
    librs_jni

# Pick up overlay for features that depend on non-open-source files
DEVICE_PACKAGE_OVERLAYS := vendor/$VENDOR/$DEVICE/overlay

\$(call inherit-product, vendor/$VENDOR/$DEVICE/$DEVICE-vendor-blobs.mk)
EOF
